#! /bin/sh
bspc monitor DP-2 -d いち に さん よん ご
bspc monitor HDMI-0 -d ろく なな はち きゅう じゅう 
bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focused_border_color \#ff79c6
bspc config normal_border_color \#BD93F9
bspc config active_border_color \#BD93F9
bspc config border_radius 10

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config automatic_scheme spiral

bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc config focus_follows_pointer true

# autostart programs
killall sxhkd
sxhkd &
killall picom 
picom &
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

feh --bg-center /home/zaibatsu/Pictures/Wallpapers/neon.png

# Launch primary and secondary bars
polybar -c ~/.config/polybar/config-primary.ini primary &
polybar -c ~/.config/polybar/config-primary.ini systray &
polybar -c ~/.config/polybar/config-primary.ini secondary
